#!/bin/sh

# http://www.webupd8.org/2012/10/how-to-reset-compiz-and-unity-in-ubuntu.html
unity_reset() {
(
  local _ANSWER
  set -vx
  echo "Check ccsm unity plugin is enabled"
  echo "Check the profile is loaded from gconf and is based on the unity template"
  echo "Press enter"; read _ANSWER
  ccsm &
  echo "Still doesn't work? reset unity/compiz..."
  echo "Press enter"; read _ANSWER
  dconf reset -f /org/compiz/
  setsid unity
  echo "Can try compiz --replace and unity --replace"
)
}

unity_launcher() {
  unity --reset-icons
}

unity_showconfig() {
  dconf dump /org/compiz/
}

unity_setup_scopes() {
  # http://www.webupd8.org/2013/10/how-to-disable-amazon-shopping.html
  # Remove shopping scope
  sudo apt-get remove unity-lens-shopping
  # disable on-line sugestions
  gsettings set com.canonical.Unity.Lenses disabled-scopes "['more_suggestions-amazon.scope', 'more_suggestions-u1ms.scope', 'more_suggestions-populartracks.scope', 'music-musicstore.scope', 'more_suggestions-ebay.scope', 'more_suggestions-ubuntushop.scope', 'more_suggestions-skimlinks.scope']"
}

# Execute command when any
[ $# -gt 0 ] && unity_"$@"
